plugins:
  - skipBotEvents: true
    uses:
        # hello-world-plugin
      - plugin: http://127.0.0.1:4000
        name: start-stop
        id: start-stop-command
        description: "Allows a user to start/stop a task without negative XP impact"
        command: "\/start|\/stop"
        example: "/start" # or "/stop"
        with:
          reviewDelayTolerance: "3 Days"
          taskStaleTimeoutDuration: "30 Days"
          startRequiresWallet: true
          maxConcurrentTasks:
            member: 2
            contributor: 2
          emptyWalletText: "Please set your wallet address with the /wallet command first and try again."
          rolesWithReviewAuthority:
            - "COLLABORATOR"
            - "OWNER"
            - "MEMBER"
            - "ADMIN"
          requiredLabelsToStart: ["Priority: 3 (High)", "Priority: 4 (Urgent)", "Priority: 5 (Emergency)"]
